
["Behavior Configuration"]
	#Using simpler aim textures
	Use_Simple_Aim_Texture = false
	#Need to continue to press Aim key to lock-on targets
	Hold_Key_To_LockOn = false
	#Need to continue to press Aim key to render aims
	Hold_Key_To_Render_Aims = true
	#Possibility to target your position when no targetable entities exists
	Can_Target_Player_Position = false
	#Possibility to render information HUD
	showHUD = true

