
["Hostile Villages settings"]
	#Percentage of how likely normal,non-zombie villages are to spawn. default: 0
	#Range: 0 ~ 100
	vanillaVillageChance = 0
	#Set higher to increase the generated population of the hostile village, default: 5
	#Range: 1 ~ 100
	hostilePopulationSize = 5
	#Whether to generate extra loot for the village, default: true
	generateLoot = true
	#List of loottables to use, default: minecraft:chests/simple_dungeon
	loottables = ["minecraft:chests/simple_dungeon"]
	#Whether to allow vanilla villagers to spawn at all, default: false
	allowVanillaVillagerSpawn = false
	#List of entity pairs which spawn in villages. Format = entity1;entity2;5;6   5 is the chance of entity2(one in five), 6 is the total weight of this whole entry to be chosen
	villageEntityTypes = ["minecraft:zombie;minecraft:stray;3;14", "minecraft:skeleton;minecraft:panda;5;6", "minecraft:husk;minecraft:spider;3;15", "minecraft:creeper;minecraft:cave_spider;3;11", "minecraft:slime;minecraft:rabbit;2;9", "minecraft:stray;minecraft:wither_skeleton;3;8", "minecraft:zombified_piglin;minecraft:pig;3;7", "minecraft:snow_golem;minecraft:sheep;3;5", "minecraft:drowned;minecraft:silverfish;3;4", "minecraft:witch;minecraft:bat;3;15", "minecraft:vindicator;minecraft:illusioner;5;9", "minecraft:pillager;minecraft:evoker;7;7"]

