
#ToLaserBlade's client side settings.
[client]
	#Add mod's vertex buffers to Minecraft's fixed buffer list.
	#Need to restart client after changing this.
	#Default: false
	useFixedVertexBuffer = false
	#Enable to render Laser Blades using multiple models. This setting is valid when useInternalModel is true. If this is true, useFixedVertexBuffer will be disabled.
	#Need to reload resource packs after changing this.
	#Default: true
	renderMultipleModels = true
	#Select type of external model to use for rendering Laser Blade (0: generated model, 1: OBJ model [not recommended]). This setting is valid when useInternalModel is false.
	#Need to reload resource packs after changing this.
	#Default: 0
	#Range: > 0
	externalModelType = 0
	#Select type of internal model to use for rendering Laser Blade (0: original model, 1: another model). This setting is valid when useInternalModel is true.
	#Need to reload resource packs after changing this.
	#Default: -1
	#Range: > -1
	internalModelType = -1
	#Enable to show update message.
	#Default: true
	showUpdateMessage = true
	#Using internal model for rendering Laser Blade. Set to false to use the model that loaded from resource packs.
	#Need to reload resource packs after changing this.
	#Default: true
	useInternalModel = true

